print("="  * 50)
print("   HELLO PYTHON CARD")
print("=" * 50)
print("Name         :Sakib Hasan")
print("Role         :IT ")
print("Email        :itsupport.hfl@habitusfashion.com")
print("Goal         :Complete 100 Days of Python")
print("Strength     :Learn, build, debug, improv")
print("=" *50)